# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: LongAT.LongATTest
PackageVersion: 1.0.0
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
UpgradeBehavior: install
Commands:
  - LongATTest
AppsAndFeaturesEntries:
  - DisplayName: Long AT Test version 1.0.0
    Publisher: Long AT
    DisplayVersion: 1.0.0
    ProductCode: '{9F573DF1-0F46-4B83-9B3B-8C6BE76A96C2}_is1'
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/vulongvy/LongATTest/releases/download/v1.0.0/LongATTest-Setup-1.0.0.exe
    InstallerSha256: 958E2AE58CBE8E1A8A47F9B6271C1354E27C26DF6AECE62B371B97CF680A12F2
ManifestType: installer
ManifestVersion: 1.6.0
